ORCA2/Controllers/ExpertisesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ORCA2.Models;

namespace ORCA2.Controllers
{
    public class ExpertisesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Expertises
        public ActionResult Index(string department, string searchString)
        {
            var DepLst = new List<string>();

            var GenreQry = from d in db.Expertises
                           orderby d.Department
                           select d.Department;

            DepLst.AddRange(GenreQry.Distinct());
            ViewBag.department = new SelectList(DepLst);

            var expertiseList = from m in db.Expertises
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                expertiseList = expertiseList.Where(s => s.Field.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(department))
            {
                expertiseList = expertiseList.Where(x => x.Department == department);
            }

            return View(expertiseList);
        }

        // GET: Expertises/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expertise expertise = db.Expertises.Find(id);
            if (expertise == null)
            {
                return HttpNotFound();
            }
            return View(expertise);
        }

        // GET: Expertises/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Expertises/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ExpertiseID,ContactEmail,Department,Field,Validated")] Expertise expertise)
        {
            if (ModelState.IsValid)
            {
                expertise.LinkedEmail = User.Identity.Name;
                expertise.Validated = false;
                db.Expertises.Add(expertise);
                db.SaveChanges();
                return RedirectToAction("Index", "Manage");
            }

            return View(expertise);
        }

        // GET: Expertises/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expertise expertise = db.Expertises.Find(id);
            if (expertise == null)
            {
                return HttpNotFound();
            }
            return View(expertise);
        }

        // POST: Expertises/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExpertiseID, Field, Department, LinkedEmail, ContactEmail, Validated")] Expertise expertise)
        {
            if (ModelState.IsValid)
            {
                //expertise.Validated = true;
                db.Entry(expertise).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expertise);
        }

        // GET: Expertises/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expertise expertise = db.Expertises.Find(id);
            if (expertise == null)
            {
                return HttpNotFound();
            }
            return View(expertise);
        }

        // POST: Expertises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Expertise expertise = db.Expertises.Find(id);
            db.Expertises.Remove(expertise);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ORCA2/Views/Expertises/Create.cshtml
@model ORCA2.Models.Expertise

@{
    ViewBag.Title = "Create";
}

<h2>Submit Expertise</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expertise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Field, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Field, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Field, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Account", "Index", "Manage")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ORCA2/Views/Expertises/Delete.cshtml
@model ORCA2.Models.Expertise

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Expertise</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Field)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Field)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ORCA2/Views/Expertises/Details.cshtml
@model ORCA2.Models.Expertise

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Expertise</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Field)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Field)
        </dd>

    </dl>
</div>
<p>
    @if (User.Identity.Name.Equals("admin@orca.com"))
    {
    @Html.ActionLink("Edit", "Edit", new { id = Model.ExpertiseID })} |
    @Html.ActionLink("Back to List", "Index")
</p>

ORCA2/Views/Expertises/Edit.cshtml
@model ORCA2.Models.Expertise

@{
    ViewBag.Title = "Edit";
}

<h2>Validate?</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expertise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ExpertiseID)

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Field, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Field, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Field, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (User.Identity.Name.Equals("admin@orca.com"))
        {
        <div class="form-group">
            @Html.LabelFor(model => model.LinkedEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LinkedEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LinkedEmail, "", new { @class = "text-danger" })
            </div>
        </div>
        }
        else
        {
            @Html.HiddenFor(model => model.ContactEmail)
        }

        <div class="form-group">
            @Html.LabelFor(model => model.ContactEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (User.Identity.Name.Equals("admin@orca.com"))
        {
        <div class="form-group">
            @Html.LabelFor(model => model.Validated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Validated)
                    @Html.ValidationMessageFor(model => model.Validated, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        }
        else
        {
            @Html.HiddenFor(model => model.Validated)
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ORCA2/Views/Expertises/Index.cshtml
@model IEnumerable<ORCA2.Models.Expertise>

@{
    ViewBag.Title = "Index";
}

<h2>Expert List</h2>

<p>
    @using (Html.BeginForm("Index", "Expertises", FormMethod.Get))
    {
        <p>
            Department: @Html.DropDownList("department", "All")
            Field: @Html.TextBox("SearchString") <br />
            <input type="submit" value="Filter" />
        </p>
    }

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Department)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Field)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Validated)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @if(item.Validated || User.Identity.Name.Equals("admin@orca.com") || User.Identity.Name.Equals(item.LinkedEmail))
        {
            @Html.HiddenFor(modelItem => item.LinkedEmail)
            <td>
                @Html.DisplayFor(modelItem => item.Department)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Field)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactEmail)
            </td>
            if (User.Identity.Name.Equals("admin@orca.com") || User.Identity.Name.Equals(item.LinkedEmail))
            {
            <td>
                @Html.DisplayFor(modelItem => item.Validated)
            </td>
            }
            else
            {
                <td>

                </td>
            }
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.ExpertiseID }) |
                @if (User.Identity.Name.Equals(item.LinkedEmail) || User.Identity.Name.Equals("admin@orca.com"))
                {
                @Html.ActionLink("Delete", "Delete", new { id = item.ExpertiseID })
                } |
                @if (!item.Validated && User.Identity.Name.Equals("admin@orca.com"))
                {
                    @Html.ActionLink("Validate", "Edit", new { id = item.ExpertiseID })
                }
            </td>
        }
    </tr>
}

</table>